--- #YAML:1.0
name: Lingua-Klingon-Segment
version: 1.01
author:
  - Philip Newton, E<lt>pne@cpan.orgE<gt>
abstract: Segment Klingon words into syllables and letters
license: bsd
requires:
  perl: 5.005_03
build_requires:
  Module::Build: 0
  Test::Differences: 0
  Test::More: 0.19
provides:
  Lingua::Klingon::Segment:
    file: lib/Lingua/Klingon/Segment.pm
    version: 1.01
generated_by: Module::Build version 0.25
