--- #YAML:1.0
name: Lingua-Klingon-Collate
version: 1.02
author:
  - Philip Newton, E<lt>pne@cpan.orgE<gt>
abstract: Sort words in Klingon sort order
license: bsd
requires:
  perl: 5.005_03
build_requires:
  Module::Build: 0
  Test::Differences: 0
  Test::More: 0.19
provides:
  Lingua::Klingon::Collate:
    file: lib/Lingua/Klingon/Collate.pm
    version: 1.02
generated_by: Module::Build version 0.25
